# Activate profile
spring.config.activate.on-profile=dev

  # MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/jirathon_auth_dev

  # Logging
logging.level.com.jirathon=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.data.mongodb=DEBUG